version: '3'

services:
  discovery-server:
    build: sergeyzem/discovery-server
    ports:
      - '8761:8761'
    networks:
      - app-network
  auth-server:
    build: sergeyzem/auth-server
    ports:
      - '9999:9999'
    depends_on:
      - postgres
      - discovery-server
    networks:
      - app-network
  words-component:
    build: sergeyzem/words-component
    environment:
      ACCESS_KEY_ID:
      SECRET_ACCESS_KEY:
    ports:
      - '8010:8010'
    depends_on:
      - postgres
      - discovery-server
    networks:
      - app-network
  ui:
    build: sergeyzem/ui
    ports:
      - '8084:8084'
    depends_on:
      - discovery-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge