PostgreSQL:
  restart: always
  image: sameersbn/postgresql:9.6-2
  ports:
    - "5433:5433"
  environment:
    - DEBUG=false

    - DB_USER=wang
    - DB_PASS=yunfei
    - DB_NAME=order
  volumes:
    - /srv/docker/postgresql:/var/lib/postgresql:Z
