version: '3.3'

services:
  discovery-server:
    build: ./discovery-server
    ports:
      - '8761:8761'
    networks:
      - app-network
  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'users'
    ports:
      - '5432:5432'
    networks:
      - app-network
  auth-server:
    build: ./auth-server
    ports:
      - '9999:9999'
    depends_on:
      - postgres
      - discovery-server
    networks:
      - app-network
  words-component:
    build: ./words-component
    ports:
      - '8010:8010'
    depends_on:
      - postgres
      - discovery-server
    networks:
      - app-network
  ui:
    build: ./ui
    ports:
      - '8084:8084'
    depends_on:
      - discovery-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge