server:
  port: 9999
  context-path: /uaa

spring:
  application:
      name: auth-server

security:
  oauth2:
    resource:
      filter-order: 3

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/