server:
  port: 9999

spring:
  application:
    name: auth-server
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        temp.use_jdbc_metadata_defaults: false
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://${POSTGRES_ADDRESS}:5432/postgres?user=postgres&password=postgres
    driver-class-name: org.postgresql.Driver
