server:
  port: 8010

spring:
  application:
    name: words-service
  jpa:
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://ec2-54-195-252-243.eu-west-1.compute.amazonaws.com:5432/d8da2s176qmgij?user=geenmmmyecipxo&password=fb4d5088b24a7f5c26d8a2b2fb8fa33a7a72d0e81a5ed02b6be0991d33f990fe
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      expose: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://${aws.eureka.host:localhost:8761}/eureka/

security:
  oauth2:
    resource:
      jwt:
        key-value:
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAphGeUMJRDLdrzLuyjJJn
          ccoXBOVtU1Id0fvCFoRH0Cgl+Kuv3cx88xT23tJCOYbaCFTbNlaULb8PgDbYn9rx
          0Wj1grkXJQbF/nE+3U+DM8UD9uSKM9VANjPlIBs2If30d+xWcP6YFe6TbbnBur2S
          /Ggu4R/wF/7kvf3dGZklW1hWW4lrgRR5ZNg5WCgB8pPOTepsyRkyfMxnJd1AZdN/
          RqKb5Aoc+395kAScC3xst1hZKnyLGiUBHsplKyAedDQ8iHoBFbseTOnk9xGhjfG9
          vII8QtgFfYSY49G1AjWZDXHnYcVASwAd8SFt6WTZD5zGbDtVzIDF7gbpik2yvX1b
          ewIDAQAB
          -----END PUBLIC KEY-----
