INSERT INTO regions (id,name) VALUES (1,'DN');
INSERT INTO regions (id,name) VALUES (2,'Wigtownshire');
INSERT INTO regions (id,name) VALUES (3,'Kon');
INSERT INTO regions (id,name) VALUES (4,'NI');
INSERT INTO regions (id,name) VALUES (5,'AN');
INSERT INTO regions (id,name) VALUES (6,'Tamil Nadu');
INSERT INTO regions (id,name) VALUES (7,'Lombardia');
INSERT INTO regions (id,name) VALUES (8,'Vermont');
INSERT INTO regions (id,name) VALUES (9,'Ontario');
INSERT INTO regions (id,name) VALUES (10,'Ankara');
INSERT INTO regions (id,name) VALUES (11,'Wisconsin');
INSERT INTO regions (id,name) VALUES (12,'Vienna');
INSERT INTO regions (id,name) VALUES (13,'M');
INSERT INTO regions (id,name) VALUES (14,'Franche-Comté');
INSERT INTO regions (id,name) VALUES (15,'OX');
INSERT INTO regions (id,name) VALUES (16,'San José');
INSERT INTO regions (id,name) VALUES (17,'Gaziantep');
INSERT INTO regions (id,name) VALUES (18,'Northwest Territories');
INSERT INTO regions (id,name) VALUES (19,'Connacht');
INSERT INTO regions (id,name) VALUES (20,'AN');
INSERT INTO regions (id,name) VALUES (21,'PE');
INSERT INTO regions (id,name) VALUES (22,'Jönköpings län');
INSERT INTO regions (id,name) VALUES (23,'Berlin');
INSERT INTO regions (id,name) VALUES (24,'Sląskie');
INSERT INTO regions (id,name) VALUES (25,'Queensland');
INSERT INTO regions (id,name) VALUES (26,'TN');
INSERT INTO regions (id,name) VALUES (27,'QLD');
INSERT INTO regions (id,name) VALUES (28,'ERM');
INSERT INTO regions (id,name) VALUES (29,'RJ');
INSERT INTO regions (id,name) VALUES (30,'Madrid');
INSERT INTO regions (id,name) VALUES (31,'Odisha');
INSERT INTO regions (id,name) VALUES (32,'North Island');
INSERT INTO regions (id,name) VALUES (33,'PA');
INSERT INTO regions (id,name) VALUES (34,'Illes Balears');
INSERT INTO regions (id,name) VALUES (35,'Nord-Pas-de-Calais');
INSERT INTO regions (id,name) VALUES (36,'SI');
INSERT INTO regions (id,name) VALUES (37,'SA');
INSERT INTO regions (id,name) VALUES (38,'O');
INSERT INTO regions (id,name) VALUES (39,'South Island');
INSERT INTO regions (id,name) VALUES (40,'NI');
INSERT INTO regions (id,name) VALUES (41,'SI');
INSERT INTO regions (id,name) VALUES (42,'Vienna');
INSERT INTO regions (id,name) VALUES (43,'São Paulo');
INSERT INTO regions (id,name) VALUES (44,'Rio Grande do Sul');
INSERT INTO regions (id,name) VALUES (45,'N.');
INSERT INTO regions (id,name) VALUES (46,'Kahramanmaraş');
INSERT INTO regions (id,name) VALUES (47,'British Columbia');
INSERT INTO regions (id,name) VALUES (48,'WI');
INSERT INTO regions (id,name) VALUES (49,'PE');
INSERT INTO regions (id,name) VALUES (50,'ON');
INSERT INTO regions (id,name) VALUES (51,'Stockholms län');
INSERT INTO regions (id,name) VALUES (52,'São Paulo');
INSERT INTO regions (id,name) VALUES (53,'Manitoba');
INSERT INTO regions (id,name) VALUES (54,'San José');
INSERT INTO regions (id,name) VALUES (55,'Île-de-France');
INSERT INTO regions (id,name) VALUES (56,'Ontario');
INSERT INTO regions (id,name) VALUES (57,'Galicia');
INSERT INTO regions (id,name) VALUES (58,'Leinster');
INSERT INTO regions (id,name) VALUES (59,'PI');
INSERT INTO regions (id,name) VALUES (60,'British Columbia');
INSERT INTO regions (id,name) VALUES (61,'Metropolitana de Santiago');
INSERT INTO regions (id,name) VALUES (62,'Comunitat Valenciana');
INSERT INTO regions (id,name) VALUES (63,'Alberta');
INSERT INTO regions (id,name) VALUES (64,'Hamburg');
INSERT INTO regions (id,name) VALUES (65,'Ontario');
INSERT INTO regions (id,name) VALUES (66,'Vermont');
INSERT INTO regions (id,name) VALUES (67,'Lombardia');
INSERT INTO regions (id,name) VALUES (68,'Vorarlberg');
INSERT INTO regions (id,name) VALUES (69,'Wie');
INSERT INTO regions (id,name) VALUES (70,'Coquimbo');
INSERT INTO regions (id,name) VALUES (71,'ON');
INSERT INTO regions (id,name) VALUES (72,'Stockholms län');
INSERT INTO regions (id,name) VALUES (73,'NSW');
INSERT INTO regions (id,name) VALUES (74,'Umbria');
INSERT INTO regions (id,name) VALUES (75,'AZ');
INSERT INTO regions (id,name) VALUES (76,'Mazowieckie');
INSERT INTO regions (id,name) VALUES (77,'British Columbia');
INSERT INTO regions (id,name) VALUES (78,'NI');
INSERT INTO regions (id,name) VALUES (79,'Brussels Hoofdstedelijk Gewest');
INSERT INTO regions (id,name) VALUES (80,'Saskatchewan');
INSERT INTO regions (id,name) VALUES (81,'TAS');
INSERT INTO regions (id,name) VALUES (82,'Ank');
INSERT INTO regions (id,name) VALUES (83,'Los Ríos');
INSERT INTO regions (id,name) VALUES (84,'WV');
INSERT INTO regions (id,name) VALUES (85,'Munster');
INSERT INTO regions (id,name) VALUES (86,'RP');
INSERT INTO regions (id,name) VALUES (87,'Metropolitana de Santiago');
INSERT INTO regions (id,name) VALUES (88,'VB');
INSERT INTO regions (id,name) VALUES (89,'KD');
INSERT INTO regions (id,name) VALUES (90,'Van');
INSERT INTO regions (id,name) VALUES (91,'HE');
INSERT INTO regions (id,name) VALUES (92,'C');
INSERT INTO regions (id,name) VALUES (93,'New South Wales');
INSERT INTO regions (id,name) VALUES (94,'Zeeland');
INSERT INTO regions (id,name) VALUES (95,'AB');
INSERT INTO regions (id,name) VALUES (96,'Victoria');
INSERT INTO regions (id,name) VALUES (97,'WE');
INSERT INTO regions (id,name) VALUES (98,'HR');
INSERT INTO regions (id,name) VALUES (99,'Chhattisgarh');
INSERT INTO regions (id,name) VALUES (100,'Trentino-Alto Adige');
