apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  labels:
    app: auth-server
spec:
  dnsConfig:
    options:
      - name: single-request-reopen
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: sergeyzem/auth-server
          ports:
            - containerPort: 9999

---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
spec:
  type: ClusterIP
  selector:
    app: auth-server
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999