apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      dnsPolicy: "None"
      dnsConfig:
        searches:
          - us-east-2.compute.internal
        options:
          - name: single-request-reopen
        nameservers:
          - 10.100.0.10
      containers:
        - name: ui
          image: sergeyzem/ui
          ports:
            - containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
    - port: 8084
      targetPort: 8084