apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
spec:
  dnsConfig:
    options:
      - name: single-request-reopen
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: sergeyzem/ui
          ports:
            - containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
    - port: 8084
      targetPort: 8084