server:
  port: 8084

spring:
  application:
      name: api-gateway

zuul:
  routes:
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      url: http://${AUTH_SERVER_ADDRESS:localhost}:9999/
    words:
      path: /words/**
      sensitiveHeaders:
      url: http://${WORDS_COMPONENT_ADDRESS:localhost}:8010/
  add-proxy-headers: true

security:
  oauth2:
    client:
      access-token-uri: http://127.0.0.1:8084/uaa/oauth/token
      user-authorization-uri: http://127.0.0.1:8084/uaa/oauth/authorize
      client-id: webapp
    resource:
          jwt:
            keyValue:
              -----BEGIN PUBLIC KEY-----
              MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAphGeUMJRDLdrzLuyjJJn
              ccoXBOVtU1Id0fvCFoRH0Cgl+Kuv3cx88xT23tJCOYbaCFTbNlaULb8PgDbYn9rx
              0Wj1grkXJQbF/nE+3U+DM8UD9uSKM9VANjPlIBs2If30d+xWcP6YFe6TbbnBur2S
              /Ggu4R/wF/7kvf3dGZklW1hWW4lrgRR5ZNg5WCgB8pPOTepsyRkyfMxnJd1AZdN/
              RqKb5Aoc+395kAScC3xst1hZKnyLGiUBHsplKyAedDQ8iHoBFbseTOnk9xGhjfG9
              vII8QtgFfYSY49G1AjWZDXHnYcVASwAd8SFt6WTZD5zGbDtVzIDF7gbpik2yvX1b
              ewIDAQAB
              -----END PUBLIC KEY-----
