server:
  port: 8010
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 8